### ISSUE TITLE
Error reading disk (mounted image) when running software.

### ISSUE THREAD

**Issue by danpos** [gbatmobile/wfs-python#1]
Hello!
I have mounted the 2TB image of a DVR whose file system is WFS (WFS0.4), which was previously mounted in the Arsenal application.
When choosing the mounted (virtual) disk as the data source, the following error is displayed in the Windows console:

> FIle: \\.\PhysicalDrive5( WFS0.4 )
> Traceback (most recent call last):
>   File "wfs_Extractor_v3.py", line 433, in onSelect
>   File "wfs_Extractor_v3.py", line 128, in carrega_imagem
> FileNotFoundError: [Errno 2] No such file or directory: '\\\\.\\PhysicalDrive5( WFS0.4 )'

What can be modified in the script to correct this issue?

**Comment by danpos** [comment]
Never mind! I've figured it out!
